/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,html}'],
};
