/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

import { colors as defaultColors } from 'tailwindcss/defaultTheme';

// This is a JSDoc type annotation that tells your editor/IDE and TypeScript
// what types are expected for this config object, providing autocompletion
// and validation for Tailwind CSS configuration.
/** @type {import('tailwindcss').Config} */

export default {
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,html}'], // files to watch for changes
	darkMode: 'class', // Enable class-based dark mode
	theme: {
		fontSize: {
			// Override default font sizes instead of creating new utilities
			// Using clamp() for responsive typography that scales with viewport
			// Values are defined as CSS custom properties in src/style.css
			'2xs': ['var(--text-2xs)', { lineHeight: 'var(--line-height-2xs)' }],
			xs: ['var(--text-xs)', { lineHeight: 'var(--line-height-xs)' }],
			sm: ['var(--text-sm)', { lineHeight: 'var(--line-height-sm)' }],
			base: ['var(--text-base)', { lineHeight: 'var(--line-height-base)' }],
			lg: ['var(--text-lg)', { lineHeight: 'var(--line-height-lg)' }],
			xl: ['var(--text-xl)', { lineHeight: 'var(--line-height-xl)', letterSpacing: 'var(--letter-spacing-xl)' }],
			'2xl': ['var(--text-2xl)', { lineHeight: 'var(--line-height-2xl)', letterSpacing: 'var(--letter-spacing-2xl)' }],
			'3xl': ['var(--text-3xl)', { lineHeight: 'var(--line-height-3xl)', letterSpacing: 'var(--letter-spacing-3xl)' }],
			'4xl': ['var(--text-4xl)', { lineHeight: 'var(--line-height-4xl)', letterSpacing: 'var(--letter-spacing-4xl)' }],
			'5xl': ['var(--text-5xl)', { lineHeight: 'var(--line-height-5xl)', letterSpacing: 'var(--letter-spacing-5xl)' }],
			'6xl': ['var(--text-6xl)', { lineHeight: 'var(--line-height-6xl)', letterSpacing: 'var(--letter-spacing-6xl)' }],
			'7xl': ['var(--text-7xl)', { lineHeight: 'var(--line-height-7xl)', letterSpacing: 'var(--letter-spacing-7xl)' }],
		},
		colors: {
			// Override default colors
			...defaultColors,
			border: 'var(--color-border)',
			input: 'var(--color-input)',
			ring: 'var(--color-ring)',
			background: 'var(--color-background)',
			foreground: 'var(--color-foreground)',
			primary: {
				DEFAULT: 'var(--color-primary)',
				foreground: 'var(--color-primary-foreground)',
			},
			secondary: {
				DEFAULT: 'var(--color-secondary)',
				foreground: 'var(--color-secondary-foreground)',
			},
			destructive: {
				DEFAULT: 'var(--color-destructive)',
				foreground: 'var(--color-destructive-foreground)',
			},
			muted: {
				DEFAULT: 'var(--color-muted)',
				foreground: 'var(--color-muted-foreground)',
			},
			accent: {
				DEFAULT: 'var(--color-accent)',
				foreground: 'var(--color-accent-foreground)',
			},
			popover: {
				DEFAULT: 'var(--color-popover)',
				foreground: 'var(--color-popover-foreground)',
			},
			card: {
				DEFAULT: 'var(--color-card)',
				foreground: 'var(--color-card-foreground)',
			},
		},
		extend: {
			// All design tokens are defined in src/style.css as CSS custom properties.
			// This ensures a single source of truth for all design values.
			// Values defined here reference those CSS variables.

			// Spacing tokens to augment Tailwind scale
			spacing: {
				18: 'var(--spacing-18)',
				88: 'var(--spacing-88)',
			},
			// Large radius for prominent CTAs/cards
			borderRadius: {
				'4xl': 'var(--radius-4xl)',
			},
			// Custom typography: map semantic font families
			fontFamily: {
				display: [
					'ui-sans-serif',
					'system-ui',
					'Segoe UI',
					'Inter',
					'Roboto',
					'Helvetica Neue',
					'Arial',
					'Noto Sans',
					'Apple Color Emoji',
					'Segoe UI Emoji',
					'Segoe UI Symbol',
					'Noto Color Emoji',
				],
				body: [
					'ui-sans-serif',
					'system-ui',
					'Inter',
					'Roboto',
					'Helvetica Neue',
					'Arial',
					'Noto Sans',
					'Apple Color Emoji',
					'Segoe UI Emoji',
					'Segoe UI Symbol',
					'Noto Color Emoji',
				],
			},
			// Subtle elevation for cards/CTAs - uses primary color from CSS tokens
			boxShadow: {
				elevated: 'var(--shadow-elevated)',
			},
			// Container defaults (so class "container" is centered with padding)
			container: {
				center: true,
				padding: {
					DEFAULT: 'var(--container-padding)',
					sm: 'var(--container-padding-sm)',
					md: 'var(--container-padding-md)',
					lg: 'var(--container-padding-lg)',
					xl: 'var(--container-padding-xl)',
				},
			},
		},
	},
	plugins: [],
};
