/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

import { cleanupScrollView, initScrollView } from '../scroll.js';

// Base URL for template paths - works in both dev and production (GitHub Pages)
const BASE_URL = import.meta.env.BASE_URL;

export const views = {
	'/': {
		templateId: 'view-home',
		templateUrl: `${BASE_URL}src/views/home.html`,
		onMount: (container) => {
			// Initialize scroll animations when home view is mounted
			initScrollView(container);
		},
		onUnmount: () => {
			// Cleanup scroll animations when navigating away
			cleanupScrollView();
		},
	},
	'/scroll': {
		templateId: 'view-scroll',
		templateUrl: `${BASE_URL}src/views/scroll.html`,
		onMount: (container) => {
			// Initialize scroll animations when view is mounted
			initScrollView(container);
		},
		onUnmount: () => {
			// Cleanup scroll animations when navigating away
			cleanupScrollView();
		},
	},
	'/about': { templateId: 'view-about', templateUrl: `${BASE_URL}src/views/about.html` },
	'/projects': { templateId: 'view-projects', templateUrl: `${BASE_URL}src/views/projects.html` },
	'/contact': { templateId: 'view-contact', templateUrl: `${BASE_URL}src/views/contact.html` },
	'/components': { templateId: 'view-components', templateUrl: `${BASE_URL}src/views/components.html` },
	404: { templateId: 'view-404', templateUrl: `${BASE_URL}src/views/404.html` },
};
