/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

export const LICENSE_HEADER_START = '/* === LICENSE-HEADER START ===';
export const LICENSE_HEADER_END = '=== LICENSE-HEADER END === */';

/**
 * Builds the standardized header block.
 * The header intentionally stays concise and references the root LICENSE files.
 */
export function renderLicenseHeader({
	projectName,
	year,
	codeLicenseRef = 'LICENSE-CODE',
	contentLicenseRef = 'LICENSE-CONTENT',
}) {
	const safeProject = projectName || 'project';
	const safeYear = String(year || new Date().getFullYear());
	return [
		LICENSE_HEADER_START,
		`This file is part of "${safeProject}".`,
		`Code license: see ${codeLicenseRef}`,
		`Content license: see ${contentLicenseRef}`,
		`© ${safeYear}. See license files for full terms.`,
		'Generated by scripts/apply-license-headers.mjs',
		LICENSE_HEADER_END,
	].join('\n');
}
