/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

import { SimpleRouter } from './router.js';
// import './style.css'; --> imported better in index.html
import './scroll.js';
import { initNavigation } from './scroll.js';
import { initThemeToggle } from './theme-toggle.js';
import { views } from './views/index.js';

// Initialize navigation menu globally (works on all routes)
initNavigation();

// Initialize router
new SimpleRouter(views);

// Initialize theme toggle (dark/light mode)
initThemeToggle();

// Handle section navigation links (smooth scroll within page)
// This is handled by scroll.js when scroll view is initialized, but we keep this as fallback
document.addEventListener('click', (e) => {
	const link = e.target.closest('a[href^="#"]');
	if (!link) return;
	const href = link.getAttribute('href');
	if (href.startsWith('#/')) return; // router link
	if (href === '#') return; // empty anchor

	const target = document.querySelector(href);
	if (target) {
		// Only use fallback if scroll.js hasn't handled it
		// scroll.js will handle smooth scrolling with proper offset
		const isSectionNavLink = link.classList.contains('section-nav-link');
		if (!isSectionNavLink) {
			// Fallback smooth scroll
			e.preventDefault();
			const navbar = document.getElementById('navbar');
			const navHeight = navbar?.offsetHeight || 80;
			target.scrollIntoView({ behavior: 'smooth', block: 'start' });
			// Adjust for navbar after scroll
			setTimeout(() => {
				window.scrollBy(0, -navHeight);
			}, 100);
		}
	}
});
