/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

import { SimpleRouter } from './router.js';
// import './style.css'; --> imported better in index.html
import { initThemeToggle } from './theme-toggle.js';
import { views } from './views/index.js';

// Initialize router
new SimpleRouter(views);

// Initialize theme toggle (dark/light mode)
initThemeToggle();

// Desplazamiento suave opcional para anclas en la página que no son enlaces del router
document.addEventListener('click', (e) => {
	const link = e.target.closest('a[href^="#"]');
	if (!link) return;
	const href = link.getAttribute('href');
	if (href.startsWith('#/')) return; // enlace del router
	const target = document.querySelector(href);
	if (target) {
		e.preventDefault();
		target.scrollIntoView({ behavior: 'smooth', block: 'start' });
	}
});
