/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

/**
 * Theme Toggle Management
 * Handles dark/light mode switching with localStorage persistence
 */

/**
 * Get the current theme from the DOM
 * @returns {'dark' | 'light'}
 */
function getCurrentTheme() {
	return document.documentElement.classList.contains('dark') ? 'dark' : 'light';
}

/**
 * Apply theme to the document and persist to localStorage
 * @param {'dark' | 'light'} theme
 */
function applyTheme(theme) {
	const root = document.documentElement;

	if (theme === 'dark') {
		root.classList.add('dark');
	} else {
		root.classList.remove('dark');
	}

	try {
		localStorage.setItem('theme', theme);
	} catch (e) {
		// Storage might be disabled; we fail silently but theme still works for this session
		console.warn('localStorage not available:', e);
	}
}

/**
 * Resolve the initial theme: localStorage > system preference > default (light)
 * @returns {'dark' | 'light'}
 */
function resolveInitialTheme() {
	try {
		const stored = localStorage.getItem('theme');
		if (stored === 'dark' || stored === 'light') {
			return stored;
		}
	} catch (e) {
		console.warn('localStorage not available:', e);
	}

	// Fallback to system preference
	const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
	return prefersDark ? 'dark' : 'light';
}

/**
 * Toggle between dark and light themes
 */
function toggleTheme() {
	const current = getCurrentTheme();
	const newTheme = current === 'dark' ? 'light' : 'dark';
	applyTheme(newTheme);
	syncButtonState();
}

/**
 * Sync the button's ARIA state and text with the current theme
 */
function syncButtonState() {
	const btn = document.querySelector('#theme-toggle');
	if (!btn) return;

	const isDark = getCurrentTheme() === 'dark';
	btn.setAttribute('aria-pressed', String(isDark));
	btn.setAttribute('aria-label', isDark ? 'Cambiar a modo claro' : 'Cambiar a modo oscuro');

	// Update button content (icon + text)
	const icon = isDark ? '☀️' : '🌙';
	const text = isDark ? 'Modo claro' : 'Modo oscuro';
	btn.innerHTML = `<span aria-hidden="true">${icon}</span> <span hidden class="sr-only sm:not-sr-only">${text}</span>`;
}

/**
 * Initialize theme toggle functionality
 */
export function initThemeToggle() {
	// Apply initial theme (before page fully renders to avoid FOUC)
	const initialTheme = resolveInitialTheme();
	applyTheme(initialTheme);

	// Set up toggle button
	const btn = document.querySelector('#theme-toggle');
	if (btn) {
		btn.addEventListener('click', toggleTheme);
		syncButtonState();
	}

	// Listen for system preference changes
	const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
	mediaQuery.addEventListener('change', (e) => {
		// Only auto-switch if user hasn't explicitly set a preference
		try {
			const stored = localStorage.getItem('theme');
			if (!stored) {
				applyTheme(e.matches ? 'dark' : 'light');
				syncButtonState();
			}
		} catch (err) {
			// Ignore localStorage errors
		}
	});
}
